baseurl = "https://www.setcorrect.com"
title = "SETCorrect LLC"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
enableEmoji = true
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = "UA-136776838-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Technical writing and editing services"
  copyright = "&copy; 2023 SETCorrect LLC. All rights reserved."
  sidebarAbout = [
    "Better known as Hillary Fraley. I'm a technical writer and editor.",
    "Currently writing security and API documentation at Dremio."
  ]
  email = "hillary.e.fraley at gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "About me"
  url = "/about/"

  [params.social]
  # facebook      = "full page or profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  email         = "hillary.e.fraley@gmail.com"
  # twitter       = "full profile url in twitter"
  linkedin      = "https://www.linkedin.com/in/hillaryfraley/"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "full profile url in instagram"
  github        = "https://github.com/hillaryfraley"
